Form Builder clip	version 1
id	type	labelItext:en-default	labelItext:nya-default	labelItext:en-image	labelItext:nya-image	constraintMsgItext:en-default	constraintMsgItext:nya-default	hintItext:en-default	hintItext:nya-default	appearance	calculateAttr	constraintAttr	constraintMsgAttr	hintItext:hasMarkdown	labelItext:hasMarkdown	rawDataAttributes	rawRepeatAttributes	relevantAttr	repeat_count	requiredAttr
/data_confidentiality	FieldList	***Data Confidentiality Clause***	***Data Confidentiality Clause***	null	null	null	null	null	null	field-list	null	null	null	null	true	null	null	null	null	null
/data_confidentiality/data_confidentiality_label	Trigger	"**FANSER Neighbor Group Registration Form!**

***Read and agree to CRS's Data Integrity and Confidentiality Clause below:***

*This serves to remind you that ***CRS*** is committed to maintaining **data integrity and confidentiality** for the people we work with.*
*You are therefore requested to guard the integrity of the data collected via this form with confidentiality!*"	"**FANSER Neighbor Group Registration Form!**

***Read and agree to CRS's Data Integrity and Confidentiality Clause below:***

*This serves to remind you that ***CRS*** is committed to maintaining **data integrity and confidentiality** for the people we work with.*
*You are therefore requested to guard the integrity of the data collected via this form with confidentiality!*"	null	null	null	null	null	null	minimal	null	null	null	null	true	null	null	null	null	null
/data_confidentiality/fo_agreed_confidentialiy	Select	***Do you agree?***	***Do you agree?***	null	null	null	null	null	null	quick	null	null	null	null	true	null	null	null	null	true
/data_confidentiality/fo_agreed_confidentialiy/yes	Choice	Yes	Yes	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/data_confidentiality/fo_agreed_confidentialiy/no	Choice	No	No	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/data_confidentiality/label_logo	Trigger	null	null	jr://file/commcare/image/crs_logo_with_tagline.png	jr://file/commcare/image/crs_logo_with_tagline.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/no_confidentiality	FieldList	***Data Condifentiality Disclaimer!***	***Data Condifentiality Disclaimer!***	null	null	null	null	null	null	field-list	null	null	null	null	true	null	null	#form/data_confidentiality/fo_agreed_confidentialiy = 'no'	null	null
/no_confidentiality/label_bang_no_confidentiality	Trigger	null	null	jr://file/commcare/image/red_bang.png	jr://file/commcare/image/red_bang.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/no_confidentiality/label_text_no_confidentiality	Trigger	"***Sorry!*** *You cannot proceed with registration if you do not agree to* ***CRS's Data Confidentiality Clause!***

*Thanks!*"	"***Sorry!*** *You cannot proceed with registration if you do not agree to* ***CRS's Data Confidentiality Clause!***

*Thanks!*"	jr://file/commcare/image/data/no_confidentiality/label_text_no_confidentiality-wr6t5j.png	jr://file/commcare/image/data/no_confidentiality/label_text_no_confidentiality-wr6t5j.png	Please Exit The Form!	Please Exit The Form!	null	null	minimal	null	9 = 0	jr:itext('no_confidentiality/label_text_no_confidentiality-constraintMsg')	null	true	null	null	null	null	null
/neighbor_group_registration	FieldList	***Neighbor Group  Registration***	***Neighbor Group  Registration***	null	null	null	null	null	null	field-list	null	null	null	null	true	null	null	null	null	null
/neighbor_group_registration/total_households_to_register	Int	"***How many Households are you registering for <output value=""#case/case_name"" />'s Neighbor Group?***"	"***How many Households are you registering for <output value=""#case/case_name"" />'s Neighbor Group?***"	null	null	The number of households should be more than 0! Please enter correct value.	The number of households should be more than 0! Please enter correct value.	"""[Ensure you have all their personal details in place]"""	"""[Ensure you have all their personal details in place]"""	null	null	. > 0	jr:itext('neighbor_group_registration/total_households_to_register-constraintMsg')	null	true	null	null	null	null	true
/neighbor_group_registration/next_label	Trigger	null	null	jr://file/commcare/image/next.png	jr://file/commcare/image/next.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member	Repeat	***Neighbor Group Member***	***Neighbor Group Member***	null	null	null	null	null	null	null	null	null	null	null	true	"{""jr:template"":""""}"	"{""jr:noAddRemove"":""true()""}"	null	#form/neighbor_group_registration/total_households_to_register	null
/neighbor_group_member/hh_array_position	DataBindOnly	null	null	null	null	null	null	null	null	null	position(..)	null	null	null	null	null	null	null	null	null
/neighbor_group_member/hh_array_real_position	DataBindOnly	null	null	null	null	null	null	null	null	null	#form/neighbor_group_member/hh_array_position + 1	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_a_name_and_sex	FieldList	Section A: Name and Sex	Section A: Name and Sex	null	null	null	null	null	null	field-list	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_a_name_and_sex/registration_for_household_no_hh_array_real_position	Trigger	"### Registration for Household No. <output value=""#form/neighbor_group_member/hh_array_real_position"" /> "	"### Registration for Household No. <output value=""#form/neighbor_group_member/hh_array_real_position"" /> "	null	null	null	null	null	null	minimal	null	null	null	null	true	null	null	null	null	null
/neighbor_group_member/section_a_name_and_sex/first_name	Text	***Q1) Enter First Name***	***Q1) Enter First Name***	null	null	A name should be written in proper case, with no spaces. E.g. Chaiwa	A name should be written in proper case, with no spaces. E.g. Chaiwa	"""[for NV No. <output value=\""#form/neighbor_group_member/hh_array_real_position\"" /> ]"""	"""[for NV No. <output value=\""#form/neighbor_group_member/hh_array_real_position\"" /> ]"""	null	null	regex(., '^[A-Z][a-z]+$')	jr:itext('neighbor_group_member/section_a_name_and_sex/first_name-constraintMsg')	null	true	null	null	null	null	true
/neighbor_group_member/section_a_name_and_sex/last_name	Text	***Q2) Enter Last Name***	***Q2) Enter Last Name***	null	null	A name should be written in proper case, with no spaces. E.g. Chaiwa	A name should be written in proper case, with no spaces. E.g. Chaiwa	"""[for NV No. <output value=\""#form/neighbor_group_member/hh_array_real_position\"" /> ]"""	"""[for NV No. <output value=\""#form/neighbor_group_member/hh_array_real_position\"" /> ]"""	null	null	regex(., '^[A-Z][a-z]+$')	jr:itext('neighbor_group_member/section_a_name_and_sex/last_name-constraintMsg')	null	true	null	null	null	null	true
/neighbor_group_member/section_a_name_and_sex/sex	Select	"*Q3) Is **<output value=""#form/neighbor_group_member/section_a_name_and_sex/first_name"" />**  ***Male or Female?***"	"*Q3) Is **<output value=""#form/neighbor_group_member/section_a_name_and_sex/first_name"" />**  ***Male or Female?***"	null	null	null	null	null	null	null	null	null	null	null	true	null	null	null	null	true
/neighbor_group_member/section_a_name_and_sex/sex/male	Choice	Male	Male	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_a_name_and_sex/sex/female	Choice	Female	Female	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_a_name_and_sex/next_label	Trigger	null	null	jr://file/commcare/image/next.png	jr://file/commcare/image/next.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_b_birth_details	FieldList	Section B: Birth Details	Section B: Birth Details	null	null	null	null	null	null	field-list	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_b_birth_details/date_of_birth	Date	***Q1) Date of Birth***	***Q1) Date of Birth***	null	null	Please enter the correct date of birth. The age range for the NV is between 14-70 years.	Please enter the correct date of birth. The age range for the NV is between 14-70 years.	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" /> ]"""	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" /> ]"""	null	null	. >= date((today() - 25550)) and . <= date((today() - 5110))	jr:itext('neighbor_group_member/section_b_birth_details/date_of_birth-constraintMsg')	null	true	null	null	null	null	true
/neighbor_group_member/section_b_birth_details/village_name	Text	***Q2) Village***	***Q2) Village***	null	null	The village name should be written in proper case, with no spaces. E.g. Kamutemeni	The village name should be written in proper case, with no spaces. E.g. Kamutemeni	"""[where <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" />  lives]"""	"""[where <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" />  lives]"""	null	null	regex(., '^[A-Z][a-z]+$')	jr:itext('neighbor_group_member/section_b_birth_details/village_name-constraintMsg')	true	true	null	null	null	null	true
/neighbor_group_member/section_b_birth_details/entered_nrc_number	PhoneNumber	***Q3) NRC Number***	***Q3) NRC Number***	null	null	The NRC must be 9 digits and no slashes.	The NRC must be 9 digits and no slashes.	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" /> , no \""/\"", just numbers, e.g. 129036341]"""	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" /> , no \""/\"", just numbers, e.g. 129036341]"""	numeric	null	regex(., '^[0-9]{9}$')	jr:itext('neighbor_group_member/section_b_birth_details/entered_nrc_number-constraintMsg')	true	true	null	null	null	null	true
/neighbor_group_member/section_b_birth_details/nrc_number	DataBindOnly	null	null	null	null	null	null	null	null	null	concat(substr(#form/neighbor_group_member/section_b_birth_details/entered_nrc_number, 0, 6), '/', substr(#form/neighbor_group_member/section_b_birth_details/entered_nrc_number, 6, 8), '/', substr(#form/neighbor_group_member/section_b_birth_details/entered_nrc_number, 8, 9))	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_b_birth_details/next_label	Trigger	null	null	jr://file/commcare/image/next.png	jr://file/commcare/image/next.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_c_contact_details	FieldList	Section C: Contact Details	Section C: Contact Details	null	null	null	null	null	null	field-list	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_c_contact_details/has_tel	Select	"***Q1) Does <output value=""#form/neighbor_group_member/section_a_name_and_sex/first_name"" />  have a phone number?***"	Kodi banja ili nayo nambala ya lamya?	null	null	null	null	null	null	null	null	null	null	null	true	null	null	null	null	true
/neighbor_group_member/section_c_contact_details/has_tel/yes	Choice	Yes	Inde	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_c_contact_details/has_tel/no	Choice	No	Ai	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_c_contact_details/entered_phone_number	PhoneNumber	***Q2) Enter Phone number***	Lowetsani nambala ya lamya	null	null	Phone number must contain 10 digits, no spaces.	Nambala ya lamya iyenera kukhala ndi manambala 10 mosatayana	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" />  ]"""	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" />  ]"""	numeric	null	regex(., '^[0-9]{10}$')	jr:itext('neighbor_group_member/section_c_contact_details/entered_phone_number-constraintMsg')	null	true	null	null	#form/neighbor_group_member/section_c_contact_details/has_tel = 'yes'	null	true
/neighbor_group_member/section_c_contact_details/phone_number	DataBindOnly	null	null	null	null	null	null	null	null	null	concat('26', #form/neighbor_group_member/section_c_contact_details/entered_phone_number)	null	null	null	null	null	null	#form/neighbor_group_member/section_c_contact_details/has_tel = 'yes'	null	null
/neighbor_group_member/section_c_contact_details/next_label	Trigger	null	null	jr://file/commcare/image/next.png	jr://file/commcare/image/next.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_c_group_details	FieldList	Section D: Group Details	Section D: Group Details	null	null	null	null	null	null	field-list	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/section_c_group_details/date_registered	Date	***Q1) Enter Date of joining Neighbor Group.***	***Q1) Enter Date of joining Neighbor Group.***	null	null	The date joined cannot be in the future!	The date joined cannot be in the future!	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" /> ]"""	"""[for <output value=\""#form/neighbor_group_member/section_a_name_and_sex/first_name\"" /> ]"""	null	null	. <= today()	jr:itext('neighbor_group_member/section_c_group_details/date_registered-constraintMsg')	null	true	null	null	null	null	true
/neighbor_group_member/section_c_group_details/next_label	Trigger	null	null	jr://file/commcare/image/next.png	jr://file/commcare/image/next.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common	Group	common	common	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/district	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/constituency	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/ward	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/chiefdom	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/camp	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/health_facility	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/supervisor	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/health_promoter	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/caregroup_name	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/full_name	DataBindOnly	null	null	null	null	null	null	null	null	null	concat(#form/neighbor_group_member/section_a_name_and_sex/first_name, ' ', #form/neighbor_group_member/section_a_name_and_sex/last_name)	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/last_date_trained	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/trained	DataBindOnly	null	null	null	null	null	null	null	null	null	'no'	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/nutrition_volunteer	DataBindOnly	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null	null
/neighbor_group_member/common/profile	DataBindOnly	null	null	null	null	null	null	null	null	null	concat(#form/neighbor_group_member/common/full_name, '[', #form/neighbor_group_member/section_b_birth_details/nrc_number, ',', #form/neighbor_group_member/section_b_birth_details/village_name, ']')	null	null	null	null	null	null	null	null	null
/end_of_form	FieldList	***Form Completed. Thanks!***	***Form Completed. Thanks!***	null	null	null	null	null	null	field-list	null	null	null	null	true	null	null	null	null	null
/end_of_form/green_bang_label	Trigger	null	null	jr://file/commcare/image/green_bang.png	jr://file/commcare/image/green_bang.png	null	null	null	null	minimal	null	null	null	null	null	null	null	null	null	null
/end_of_form/end_of_form_label	Trigger	"*You have reached the end of the form! You can now **SAVE** the form by tapping on ""**FINISH**"" on the navigation bar above!*"	"*You have reached the end of the form! You can now **SAVE** the form by tapping on ""**FINISH**"" on the navigation bar above!*"	jr://file/commcare/image/crs_logo_with_tagline.png	jr://file/commcare/image/crs_logo_with_tagline.png	null	null	null	null	minimal	null	null	null	null	true	null	null	null	null	null